# Generated by Django 4.2.7 on 2023-11-21 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pokemodel',
            options={},
        ),
    ]
