# Generated by Django 4.2.7 on 2023-11-21 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_pokemodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemodel',
            name='second_type',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Fire', 'Fire'), ('Water', 'Water'), ('Electric', 'Electric'), ('Grass', 'Grass'), ('Ice', 'Ice'), ('Fighting', 'Fighting'), ('Poison', 'Poison'), ('Ground', 'Ground'), ('Flying', 'Flying'), ('Psychic', 'Psychic'), ('Bug', 'Bug'), ('Rock', 'Rock'), ('Ghost', 'Ghost'), ('Dragon', 'Dragon'), ('Dark', 'Dark'), ('Steel', 'Steel'), ('Fairy', 'Fairy')], max_length=100, null=True),
        ),
    ]
