# Generated by Django 4.2.7 on 2023-11-21 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_pokemodel_second_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Afisha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.PositiveIntegerField(default=1)),
                ('region', models.CharField(max_length=100)),
            ],
        ),
    ]
